#!/usr/bin/env sh
set -ex			    # Stop on first error and log all commands

CC="cc"
CFLAGS="-Wall -Wextra -Wshadow -Wswitch-enum -pedantic -std=c89"

$CC $CFLAGS -o 01a 01a.c
./01a 01.in0
./01a 01.in1
$CC $CFLAGS -o 01b 01b.c
./01b 01.in0
./01b 01.in1
