#!/usr/bin/env sh
set -ex			    # Stop on first error and log all commands

CC="cc"
CFLAGS="-Wall -Wextra -Wshadow -Wswitch-enum -pedantic -std=c89"

# Day 1
$CC $CFLAGS -o 01a 01a.c
expr $(./01a <01.in0) = 24000
expr $(./01a <01.in1) = 68923
$CC $CFLAGS -o 01b 01b.c
expr $(./01b <01.in0) = 45000
expr $(./01b <01.in1) = 200044

# Day 2
$CC $CFLAGS -o 02a 02a.c
expr $(./02a <02.in0) = 15
expr $(./02a <02.in1) = 15572
$CC $CFLAGS -o 02b 02b.c
expr $(./02b <02.in0) = 12
expr $(./02b <02.in1) = 16098

# Day 3
$CC $CFLAGS -o 03a 03a.c
expr $(./03a <03.in0) = 157
expr $(./03a <03.in1) = 7875
$CC $CFLAGS -o 03b 03b.c
expr $(./03b <03.in0) = 70
expr $(./03b <03.in1) = 2479

# Day 4
$CC $CFLAGS -o 04a 04a.c
expr $(./04a <04.in0) = 2
expr $(./04a <04.in1) = 580
$CC $CFLAGS -o 04b 04b.c
expr $(./04b <04.in0) = 4
expr $(./04b <04.in1) = 895

# Day 5
$CC $CFLAGS -o 05a 05a.c
expr $(./05a <05.in0) = CMZ
expr $(./05a <05.in1) = QNHWJVJZW
$CC $CFLAGS -o 05b 05b.c
expr $(./05b <05.in0) = MCD
expr $(./05b <05.in1) = BPCZJLFJW

# Day 6
$CC $CFLAGS -o 06a 06a.c
expr $(./06a <06.in0) = 7
expr $(./06a <06.in1) = 5
expr $(./06a <06.in2) = 6
expr $(./06a <06.in3) = 10
expr $(./06a <06.in4) = 11
expr $(./06a <06.in5) = 1300
$CC $CFLAGS -o 06b 06b.c
expr $(./06b <06.in0) = 19
expr $(./06b <06.in1) = 23
expr $(./06b <06.in2) = 23
expr $(./06b <06.in3) = 29
expr $(./06b <06.in4) = 26
expr $(./06b <06.in5) = 3986
